### PR TITLE
Fix #50 - FullDate() respect month days.

### LINKED ISSUE #50: randomdata.FullDate() can return invalid dates
I leverage the `randomdata.FullDate()` function call in some unit tests by parsing the random full dates into time.Time structs. : 
```
			t, err = time.Parse(dateLayout, randomdata.FullDate())
			if err != nil {
				Fail(err.Error())
			}
```

**What I expected to see** : The above fail handler would not be called

**What I actually saw** :  `parsing time "Tuesday 29 Feb 2018": day out of range`

This causes intermittent unit test failures.

### PR DESCRIPTION
**Pull request by n1try**
### Background
The PR attempts to resolve bug [50](https://github.com/Pallinder/go-randomdata/issues/50). Generating dates will respect varying number of days in a month, e.g. February usually only has 28 days. This is accomplished by generating actual date objects instead of concatenating number strings.

### Changes
*MANDATORY*
- Fix `randomdata.FullDate()` method
- Add tests

### Checklist
- [x] Tests added
- [x] Documentation updated to include changes (if needed)
- [x] Gofmt run on your code

### CODE REVIEW

File: random_data_test.go [hunk 1]
```diff
@@ -340,11 +340,30 @@ func TestFullDate(t *testing.T) {
...
+	if err != nil {
+		t.Error("Invalid random full date")
+	}
+
+	if fulldateOne == fulldateTwo {
+		t.Error("Generated same full date twice in a row")
+	}
 }
 
+func TestFullDatePenetration(t *testing.T) {
```
Comment (ericadams) [inline random_data_test.go]: 👍  Nice test

File: random_data.go [hunk 2]
```diff
@@ -324,11 +324,12 @@ func Month() string {
 // FullDate returns full date
 func FullDate() string {
 	timestamp := time.Now()
-	day := Day()
-	month := Month()
 	year := timestamp.Year()
-	fullDate := day + " " + strconv.Itoa(Number(1, 30)) + " " + month[0:3] + " " + strconv.Itoa(year)
-	return fullDate
+	month := Number(1, 13)
+	maxDay := time.Date(year, time.Month(month), 1, 0, 0, 0, 0, time.UTC).AddDate(0, 1, -1).Day()
```
Comment (ericadams) [inline random_data.go]: Would this be clearer as `maxDay := time.Date(year, time.Month(month + 1), 0, 0, 0, 0, 0, time.UTC).Day()`?
https://play.golang.org/p/Xe6Us-aWh3F

**Comment by n1try** [comment]
Thanks! I have implemented your change requests.

**Comment by n1try** [comment]
News on this?

**Comment by Pallinder** [comment]
Great stuff! Sorry, been a ton of stuff lately.

**Comment by Pallinder** [comment]
Could you improve the description on the PR? Then I can rely on that description when merging.

**Comment by Pallinder** [comment]
Awesome reviews @ericadams thanks!

**Comment by n1try** [comment]
> Could you improve the description on the PR? Then I can rely on that description when merging.

Done

**Comment by ericadams** [comment]
@n1try the maintainer may have meant he wanted description in the PR title/heading (at least, that's what my vs code git plugin looks at)

**Comment by Pallinder** [comment]
Awesome. Will merge this together with the other PR:s ones we've gotten the descriptions to be inline with the template.

**Comment by Pallinder** [comment]
Template can be found at https://github.com/Pallinder/go-randomdata/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by n1try** [comment]
Done.

**Comment by ericadams** [comment]
sweet, thanks @n1try !

**Comment by Pallinder** [comment]
Merging this and including in 1.1.0 great stuff!
